# Generated by Django 4.0.5 on 2022-06-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('filesharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='remark',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
