# Generated by Django 4.0.5 on 2022-06-06 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('filesharing', '0002_alter_file_file_alter_file_remark_alter_file_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='filehash',
            new_name='file_hash',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='filename',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='url',
            new_name='file_url',
        ),
    ]
