# Generated by Django 4.0.5 on 2022-06-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('filesharing', '0003_rename_filehash_file_file_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_hash',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
