# Generated by Django 4.0.5 on 2022-06-09 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('filesharing', '0004_alter_file_file_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_hash',
            new_name='hash',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_name',
            new_name='name',
        ),
    ]
