# Generated by Django 4.0.5 on 2022-06-09 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('filesharing', '0005_rename_file_file_content_rename_file_hash_file_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_url',
            new_name='url',
        ),
    ]
