# Generated by Django 4.0.5 on 2022-06-09 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('filesharing', '0006_rename_file_url_file_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='timestamp',
            new_name='created',
        ),
    ]
