# Generated by Django 4.0.5 on 2022-06-11 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('filesharing', '0007_rename_timestamp_file_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='content',
            new_name='file',
        ),
    ]
