# Generated by Django 4.0.5 on 2022-06-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('filesharing', '0008_rename_content_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mimetype',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
