# Generated by Django 4.0.5 on 2022-06-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('filesharing', '0010_rename_isrequested_file_blocking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
