# Generated by Django 4.0.5 on 2022-06-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('filesharing', '0011_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
