# Generated by Django 4.0.5 on 2022-06-17 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('filesharing', '0012_alter_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='unblocking_information',
            new_name='description',
        ),
    ]
