# Generated by Django 4.0.5 on 2022-06-28 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0013_rename_unblocking_information_file_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_downloaded',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 28, 19, 30, 17, 3983)),
        ),
    ]
